image:
    - Visual Studio 2017

platform:
    - x64

configuration:
    - Debug
    - Release

matrix:
    fast_finish: true

init:
    - cmd: cmake --version
    - cmd: msbuild /version

before_build:
    - cd c:\tools\vcpkg
    - git pull
    - .\bootstrap-vcpkg.bat
    - vcpkg install sdl2:x64-windows
    - vcpkg integrate install
    - cd %APPVEYOR_BUILD_FOLDER%

build_script:
    - mkdir build
    - cd build
    - cmake -A%PLATFORM% -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DSOFTRENDER_BUILD_TESTS=ON -DCMAKE_TOOLCHAIN_FILE=c:\tools\vcpkg\scripts\buildsystems\vcpkg.cmake ..
    - cmake --build .

cache: c:\tools\vcpkg\installed\
