language: c++

matrix:
    include:
        - os: linux
        - dist: bionic
          env:
              - TARGET=x86_64-unknown-linux-gnu
              - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
          addons:
              apt:
                  update: true
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - cmake
                      - g++-8
                      - libsdl2-dev
          compiler: g++-8
        - os: linux
        - dist: bionic
          env:
              - TARGET=x86_64-unknown-linux-gnu
              - MATRIX_EVAL="CC=clang-8 && CXX=clang++-8"
          addons:
              apt:
                  update: true
                  sources:
                      - llvm-toolchain-bionic-8
                      - ubuntu-toolchain-r-test
                  packages:
                      - cmake
                      - clang-8
                      - libstdc++-8-dev
                      - libsdl2-dev
          compiler: clang++-8
        - os: osx
          osx_image: xcode11
          env:
              - MATRIX_EVAL="brew install sdl2; brew link --overwrite gcc && CC=gcc && CXX=g++
          compiler: g++
        - os: osx
          osx_image: xcode11
          compiler: clang++

script:
    - mkdir build
    - cd build
    - eval "${MATRIX_EVAL}"
    - cmake -DSOFTRENDER_BUILD_TESTS=ON ..
    - make -j$(nproc)
    - cd tests
    - ctest --verbose || true

notifications:
    email:
        on_success: never
        on_failure: change

