trigger:
    tags:
        include:
        - v*
    branches:
        include:
        - master
        - development

variables:
    SOFTRENDER_VERSION: nightly

jobs:
    - job: Linux_Debug_GCC9
      pool:
          vmImage: 'ubuntu-16.04'
      variables:
          CODECOV_TOKEN: c3ade3e3-5a6c-4f0a-814c-0538338d1116
      steps:
      - script: |
          set -e
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt update
          sudo apt install -y gcc-9 g++-9
        displayName: Install gcc-9
      - script: |
          vcpkg install sdl2
        displayName: Install SDL2
      - script: |
          set -e
          mkdir build && cd build
          export CC=gcc-9
          export CXX=g++-9
          # Turn off undefined sanitizer because of ubuntu-16.04 bug
          cmake -DCMAKE_BUILD_TYPE=Debug \
                -DSOFTRENDER_COVERAGE=ON \
                -DSOFTRENDER_BUILD_TESTS=ON \
                -DSOFTRENDER_MOCKING=ON \
                -DSOFTRENDER_USE_ADDRESS_SANITIZER=ON \
                -DSOFTRENDER_USE_LEAK_SANITIZER=ON \
                -DSOFTRENDER_USE_UNDEFINED_SANITIZER=OFF \
                -DCMAKE_TOOLCHAIN_FILE=/usr/local/share/vcpkg/scripts/buildsystems/vcpkg.cmake ..
          cmake --build . --config Debug
        displayName: Build SoftRender and it's tests
      - script: |
          set -e
          cd build/tests/
          ctest -V
        displayName: Run the tests
      - script: |
          cd build/
          ../scripts/codecov-io-azure.sh
        displayName: Publish code coverage
